import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Announcement from "./components/announcement";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ClerkProvider,  SignInButton, SignedIn, SignedOut } from '@clerk/nextjs'
import './globals.css'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <ClerkProvider>
    <html lang="en">
    
      <body>
      
      <header>
      <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              {/* <UserButton /> */}
            </SignedIn>
          </header>
        <div className="w-full p-10 md:m-2">
              <Announcement/>
              <Navbar/>
              <main>{children}</main>
              <Footer/>
               
            </div>
            
              
      </body>
    </html>
    </ClerkProvider>
  );
}
  






